/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.klinikhewan;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Nafisah
 */
public class Cekkandang extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cekkandang.class.getName());
    
    int idHewanMasuk;

    public void tangkapIdHewan(int id) {
    this.idHewanMasuk = id;
    }
    /**
     * Creates new form Cekkandang
     */
    public Cekkandang() {
        initComponents();
        cekKetersediaanKandang();
    }
    public void cekKetersediaanKandang() {
    // 1. Membuat kerangka model tabel baru
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Nomor Kandang");
    model.addColumn("Status");

    // Daftar nama kandang sesuai dengan tampilan di desain visual (KDG01 - KDG05)
    String[] daftarKandang = {"KDG01", "KDG02", "KDG03", "KDG04", "KDG05"};

    // 2. Validasi: Jika salah satu tanggal belum diisi, tampilkan status kosong dulu
    if (jDateChooser1.getDate() == null || jDateChooser2.getDate() == null) {
        for (String kandang : daftarKandang) {
            model.addRow(new Object[]{kandang, "Silakan pilih tanggal"});
        }
        jTable1.setModel(model); // Ganti jTable1 dengan nama variabel tabel kandangmu
        return;
    }

    try {
        // 3. Format kedua tanggal pilihan dari JDateChooser
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tglMulaiPilihan = sdf.format(jDateChooser1.getDate()); // Kalender pertama (dari)
        String tglSelesaiPilihan = sdf.format(jDateChooser2.getDate()); // Kalender kedua (sampai)

        Connection conn = testkoneksi.getKoneksi();

        // 4. Lakukan perulangan (loop) untuk memeriksa status tiap kandang di database
        for (String kandang : daftarKandang) {
            
            // Query SQL dengan rumus overlap rentang tanggal
            String sql = "SELECT COUNT(*) FROM tb_penitipan WHERE nomor_kandang = ? " +
                         "AND tanggal_masuk <= ? AND tanggal_keluar >= ?";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, kandang);
            pst.setString(2, tglSelesaiPilihan); // Mengisi batas tanggal_masuk <= selesai
            pst.setString(3, tglMulaiPilihan);   // Mengisi batas tanggal_keluar >= mulai

            ResultSet rs = pst.executeQuery();
            
            String status = "VALID / Kosong"; // Default jika tidak ditemukan bentrokan
            
            if (rs.next()) {
                int jumlahBookingBentrokan = rs.getInt(1);
                // Jika jumlahnya lebih dari 0, berarti tanggal tersebut sudah dipesan orang lain
                if (jumlahBookingBentrokan > 0) {
                    status = "INVALID / Sudah Dibooking";
                }
            }

            // Masukkan hasil pemeriksaan ke baris tabel
            model.addRow(new Object[]{kandang, status});
        }

        // 5. Perbarui tampilan tabel dengan data status yang baru
        jTable1.setModel(model); // Ganti jTable1 dengan nama variabel tabel kandangmu

    } catch (Exception e) {
        System.out.println("Error cek ketersediaan kandang: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setText("CEK KETERSEDIAAN KANDANG");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"KDG01", null},
                {"KDG02", null},
                {"KDG03", null},
                {"KDG04", null},
                {"KDG05", null}
            },
            new String [] {
                "Nomor Kandang", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Next");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Back");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jDateChooser1.addPropertyChangeListener(this::jDateChooser1PropertyChange);

        jDateChooser2.addPropertyChangeListener(this::jDateChooser2PropertyChange);

        jLabel2.setText("sampai");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Penitipan pen = new Penitipan();
        pen.tangkapIdHewan(this.idHewanMasuk); 
        pen.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
       cekKetersediaanKandang();
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jDateChooser2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser2PropertyChange
        cekKetersediaanKandang();
    }//GEN-LAST:event_jDateChooser2PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cekkandang().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
