/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.klinikhewan;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
/**
 *
 * @author LENOVO
 */

public class JadwalPerawatan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JadwalPerawatan.class.getName());
    
    int idHewanFinal;
    String jenisPerawatanFinal;

    public void tangkapDataDariFormPerawatan(int id, String perawatan) {
        this.idHewanFinal = id;
        this.jenisPerawatanFinal = perawatan;
    }
    /**
     * Creates new form JadwalPerawatan
     */
    public JadwalPerawatan() {
        initComponents();
        
        // Menambahkan pendeteksi klik otomatis pada JDayChooser
        jDayChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cekValidasiJadwal();
            }
        });
    }
    public void cekValidasiJadwal() {
        try {
            int hariDipilih = jDayChooser1.getDay();
            Calendar calPilihan = Calendar.getInstance();
            calPilihan.set(Calendar.DAY_OF_MONTH, hariDipilih);

            Calendar calHariIni = Calendar.getInstance();

            // 1. Validasi Masa Lalu
            if (hariDipilih < calHariIni.get(Calendar.DAY_OF_MONTH)) {
                lblStatus.setText("INVALID: Tanggal sudah terlewat!");
                lblStatus.setForeground(Color.RED);
                return;
            }

            // 2. Siapkan data untuk dicek ke Database
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String formatTanggal = sdf.format(calPilihan.getTime());
            String jamDipilih = jComboBox1.getSelectedItem().toString();

            Connection conn = testkoneksi.getKoneksi();
            String sql = "SELECT * FROM tb_perawatan WHERE tanggal = ? AND jam = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, formatTanggal);
            pst.setString(2, jamDipilih);

            ResultSet rs = pst.executeQuery();

            // 3. Tentukan hasil validasi
            if (rs.next()) {
                lblStatus.setText("INVALID: Jadwal Penuh!");
                lblStatus.setForeground(Color.RED);
            } else {
                lblStatus.setText("VALID: Jadwal Tersedia");
                lblStatus.setForeground(new Color(0, 153, 0)); // Hijau
            }
        } catch (Exception e) {
            System.out.println("Error cek jadwal: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jLabel3 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel1.setText("JADWAL PERAWATAN");

        jButton2.setText("Back");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton1.setText("Next");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel2.setText("Jam:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09.00", "10.00", "11.00", "13.00", "14.00", "15.00", "16.00", "17.00", "18.00", "19.00", "20.00" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jLabel3.setText("Tanggal:");

        lblStatus.setText("jTextField1");
        lblStatus.addActionListener(this::lblStatusActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(115, 115, 115))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addGap(308, 308, 308)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jDayChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDayChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PilihJenisLayanan PJL = new
        PilihJenisLayanan();

        PJL.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        cekValidasiJadwal();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (lblStatus.getText().contains("INVALID") || lblStatus.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tidak dapat menyimpan. Silakan pilih jadwal yang VALID!");
            return;
        }

        try {
            Connection conn = testkoneksi.getKoneksi();
            String sql = "INSERT INTO tb_perawatan (id_hewan, jenis_perawatan, tanggal, jam) VALUES (?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);

            // Parameter 1 & 2: ID dan Jenis Perawatan (dari estafet)
            pst.setInt(1, idHewanFinal);
            pst.setString(2, jenisPerawatanFinal);

            // Parameter 3: Mengubah JDayChooser jadi YYYY-MM-DD
            int hari = jDayChooser1.getDay();
            Calendar cal = Calendar.getInstance();
            cal.set(Calendar.DAY_OF_MONTH, hari);
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String formatTanggal = sdf.format(cal.getTime());
            
            pst.setString(3, formatTanggal);
            
            // Parameter 4: Ambil Jam
            pst.setString(4, jComboBox1.getSelectedItem().toString());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Jadwal Perawatan Berhasil Disimpan!");

            // Lanjut ke Form Bukti Penitipan
            // BuktiPenitipan bp = new BuktiPenitipan();
            // bp.setVisible(true);
            // this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan jadwal: " + e.getMessage());
        }
    }                                        

    public static void main(String args[]) {
        // ... (Biarkan kode Look and feel bawaanmu di sini) ...
        java.awt.EventQueue.invokeLater(() -> new JadwalPerawatan().setVisible(true));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField lblStatus;
    // End of variables declaration//GEN-END:variables
}
